quiz_homepage:
    path:     /
    defaults: { _controller: QuizBundle:Quiz:index }

quiz_create_quiz:
    path:     /create/quiz
    defaults: { _controller: QuizBundle:Quiz:create }

quiz_create_quiz_two:
    path:     /create/next/quiz/{id}
    defaults: { _controller: QuizBundle:Question:create }

quiz_create_categorie:
    path:     /create/categorie
    defaults: { _controller: QuizBundle:Categorie:create }

quiz_edit_categorie:
    path: /edit/categorie
    defaults: { _controller: QuizBundle:Categorie:edit }

quiz_delete_categorie:
    path: /delete/categorie
    defaults: { _controller: QuizBundle:Categorie:delete }

quiz_create_theme:
    path: /create/theme
    defaults: { _controller: QuizBundle:Theme:create }

quiz_edit_theme:
    path: /edit/theme
    defaults: { _controller: QuizBundle:Theme:edit }

quiz_delete_theme:
    path: /delete/theme
    defaults: { _controller: QuizBundle:Theme:delete }